print("             biodata mahasiswa    ")
print("             ****************")
nama = input("nilai absen   :")
harga = input("nilai tugas   :")
kode = input("nilai ulangan :")
jumlah = input("   : ")
total = int(jumlah) * int(harga)

print("=====================================")
print("HAGRGA MAINAN ANAK=25000")
print(" = " + str(nama))
print("  = " + str(kode))
print("       = " + str(jumlah))
print("  = " + str(total))
